apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
  postgresql.conf: |
    # Custom PostgreSQL configuration
    listen_addresses = '*'
    max_connections = {{ .Values.postgresql.maxConnections | default 100 }}
    shared_buffers = '{{ .Values.postgresql.sharedBuffers | default "128MB" }}'
    effective_cache_size = '{{ .Values.postgresql.effectiveCacheSize | default "256MB" }}'
    log_statement = '{{ .Values.postgresql.logStatement | default "none" }}'

    {{- if .Values.customConfig.enabled }}
{{ .Values.customConfig.config | indent 4 }}
    {{- end }}
