apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  postgresql.conf: |
    # Custom PostgreSQL configuration
    listen_addresses = '*'
    max_connections = {{ .Values.postgresql.maxConnections | default 100 }}
    shared_buffers = '{{ .Values.postgresql.sharedBuffers | default "128MB" }}'
    effective_cache_size = '{{ .Values.postgresql.effectiveCacheSize | default "256MB" }}'
    log_statement = '{{ .Values.postgresql.logStatement | default "none" }}'
    
    {{- if .Values.customConfig.enabled }}
    {{ .Values.customConfig.config | nindent 4 }}
    {{- end }}