apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  encryptedData:
    password: AgCFnDJoI7MZ36GEnCjO5we2qZv3NtAhCvWIfL9VFlRedsSONgv0jYXWxMnBrq+Yc4NI/7s7qQtvml197H6pvYobxmU6pbCT1iRn0W+qR6d8Nt7KN7ErHF2Xbp8Oik0FefUF9GgEug0R2OykPZs/z92EcBam0fjFQaNxHeUwPB596nfIALuLZu9cV7sKG/qU/xSTdkcOataEByWHCnxpPMovYeTgONdyyDVZKdNqzYoYbkVCQNK3n2oj6hczitFXbswbZFLFHrM0hvccZ8YVeGVEFTU41+jXjf7zUnDI+ZQ85nmsPod2jsB1mHCI9REIJNRQTRT2JkT4gGuZfrjw/k1546jzalnZYKQwt8nogD2Lv6FvkMIW8JBsTdPQQcdxOUEqaMwHmVecpiB6+dviMG4xj/tAPsvVd0S/7mZrkjO/f/kVT+xPTwuoJm2CkN7v4FwkjYS0rgtw07FWMzX0E6ZkjuZ8v/AFObHS8mDnHaVRM4c9PxoehuLk9zU28ZAJ0j4SwxULmf/1ihhOUnCUgGMNWhtGFS5ULwNhNHVY7Rj2RbD+fN5NyhpHHnXLqqm6SSIOq6Bri2OkFh1mydWZ8bHjGhDLlofwX2nbwYF3uH0uRIWLtVUx7LeccyQR+zNsjGQUag7QWJALqHPN3dbZ+Rje8W2a7vfv4YOJcXstgTXcDQan1rlGSaaMyXGYcw1asJl9x7whTOL+QRpoSspvGQ==
  template:
    metadata:
      name: postgres-secret
      namespace: db
    type: Opaque