apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      name: postgres
  selector:
    app: {{ include "postgres.name" . | quote }}