pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:24.0.7-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
  - name: jnlp
    image: jenkins/inbound-agent:latest
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
'''
        }
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/IvanRoussev/iroussev.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                container('docker') {
                    dir('frontend') {
                        script {
                            docker.build("iroussevcom/frontend:${env.BUILD_ID}")
                        }
                    }
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                container('docker') {
                    dir('frontend') {
                        script {
                            docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                                docker.image("iroussevcom/frontend:${env.BUILD_ID}").push()
                                docker.image("iroussevcom/frontend:${env.BUILD_ID}").push('latest')
                            }
                        }
                    }
                }
            }
        }
    }
}