pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/iroussev.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        docker.build("iroussevcom/frontend:${env.BUILD_ID}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', 'DOCKERHUB_CREDENTIALS') {
                            docker.image("iroussev/frontend:${env.BUILD_ID}").push()
                            docker.image("iroussev/frontend:${env.BUILD_ID}").push('latest')
                        }
                    } 
                }
            }
        }
    }
}
