resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

jenkins:
  controller:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: jenkins.iroussev.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        acme.cert-manager.io/http01-edit-in-place: "true"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8080
      tls:
        - secretName: jenkins-tls
          hosts:
            - jenkins.iroussev.com

  agent:
    additionalContainers:
      - sideContainerName: dind
        image:
          repository: docker
          tag: dind
        command: dockerd-entrypoint.sh
        args: ""
        privileged: true
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi