resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

jenkins:
  controller:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: jenkins.iroussev.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # Allow HTTP access for ACME challenges (no redirect)
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        # Alternatively, use this annotation to allow HTTP for challenge path only
        cert-manager.io/issue-temporary-certificate: "true"
        acme.cert-manager.io/http01-edit-in-place: "true"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8080
      tls:
        - secretName: jenkins-tls
          hosts:
            - jenkins.iroussev.com