jenkins:
  controller:

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: jenkins.iroussev.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8080
      tls:
        - secretName: jenkins-tls
          hosts:
            - jenkins.iroussev.com