resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

jenkins:
  controller:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: jenkins.iroussev.com
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8080
      tls:
        - secretName: jenkins-tls
          hosts:
            - jenkins.iroussev.com

    paths: 
      - path: /
        pathType: Prefix



    tls: 
      - secretName: jenkins-tls
        hosts:
          - jenkins.iroussev.com
