resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

controller:
  ingress:
    enabled: true
    ingressClassName: nginx
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hostName: jenkins.iroussev.com

    paths: 
      - path: /
        pathType: Prefix



    tls: 
      - secretName: jenkins-tls
        hosts:
          - jenkins.iroussev.com
