apiVersion: v2
name: postgres-operator
description: Helm chart for Zalando PostgreSQL Operator
type: application
version: 0.1.0
appVersion: "1.14.0"   # example version (you can update this)
dependencies:
  - name: postgres-operator
    version: "1.14.0"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
  - name: postgres-operator-ui
    version: "1.14.0"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui"