grafana:  
  image:
    registry: docker.io
    repository: grafana/grafana
    tag: ""
    sha: ""
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: grafana.iroussev.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    path: /
    pathType: Prefix
    hosts:
      - grafana.iroussev.com
    tls:
    - secretName: grafana-iroussev-tls
      hosts:
        - grafana.iroussev.com

  persistence:
    type: pvc
    enabled: true
    volumeName: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
    lookupVolumeName: true

  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ tpl (.Values.ingress.hosts | first) . }}{{ else }}''{{ end }}"


