ingress-nginx:
  controller:
    replicaCount: 2
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local  
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi