
replicaCount: 1

image:
  repository: iroussevcom/attack-cluster
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: apps.iroussev.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: attack-cluster-tls
     hosts:
       - apps.iroussev.com


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

httpRoute:
  enabled: false