apiVersion: v2
name: ingress-nginx
description: NGINX Ingress Controller
type: application
version: 1.0.0
dependencies:
  - name: ingress-nginx
    version: "4.13.0"  # Use latest stable version
    repository: https://kubernetes.github.io/ingress-nginx
