argo-cd:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: argo.iroussev.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/tls-acme: "true"
      path: /
      pathType: Prefix
      tls:
        - secretName: argocd-tls
          hosts:
            - argo.iroussev.com


    extraArgs:
      - --insecure

  configs:
    params:
      server.insecure: true  # Allows HTTPS termination at NGINX ingress


global:
  # Disable the built-in Ingress from templates
  ingress:
    enabled: false