server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: argo.iroussev.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argo.iroussev.com