argo-cd:  
  global:
    domain: argo.iroussev.com

  configs:
    params:
      server.insecure: "true"

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
      
      # Hostname
      hostname: argo.iroussev.com
      
      # Path configuration
      path: /
      pathType: Prefix
      
      # Enable TLS
      tls: true
      

    certificate:
      enabled: true
      domain: argo.iroussev.com
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-prod


  # Notifications configuration
  notifications:
    enabled: true
    argocdUrl: https://argo.iroussev.com