apiVersion: v2
name: metallb
description: MetalLB LoadBalancer for bare-metal Kubernetes
type: application
version: 0.15.2
dependencies:
  - name: metallb
    version: "0.15.2"
    repository: "https://metallb.github.io/metallb"
