name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
      - name: Build
        working-directory: attack-cluster
        run: |
          go mod tidy
          go build -v ./...

      - name: Test
        working-directory: attack-cluster
        run: go test -v ./...

  Build:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: attack-cluster
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/attack-cluster:latest
            ${{ vars.DOCKERHUB_USERNAME }}/attack-cluster:${{ github.sha }}