# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Build
      working-directory: attack-cluster
      run: |
        go mod tidy
        go build -v ./...

    - name: Test
      working-directory: attack-cluster
      run: go test -v ./...
      
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: attack-cluster
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/attack-cluster:latest
          ghcr.io/${{ github.repository_owner }}/attack-cluster:${{ github.sha }}
